[theme]
# Главный акцентный цвет (кнопки, ползунки)
primaryColor = "#11BF8E"

# Цвет фона приложения (оставим чистый белый для корпоративного стиля)
backgroundColor = "#FFFFFF"

# Цвет боковой панели и фонов карточек (самый светлый из вашей палитры)
secondaryBackgroundColor = "#CEF2EC"

# Основной цвет текста (самый темный из палитры для контраста)
textColor = "#085e45"

font = "sans serif"

[server]
maxUploadSize = 1000  # Дозволяє файли до 1 ГБ